#google:
#  client:
#    clientId: 541555327940-in06jhn0n4pu9vrfn42aubbcuoppbsih.apps.googleusercontent.com
#    clientSecret: Ny_qKOsXUBT5jCDAgQKvTQby
#    accessTokenUri: https://accounts.google.com/o/oauth2/token
#    scope: email, profile
#  resource:
#    userInfoUri: https://www.googleapis.com/oauth2/v2/userinfo
#
#kakao:
#  client:
#    clientId: 9b7e730a78399b4f6d1af01ddd236ff9
#    accessTokenUri: https://kauth.kakao.com/oauth/token
#    userAuthorizationUri: https://kauth.kakao.com/oauth/authorize
#  resource:
#    userInfoUri: https://kapi.kakao.com/v1/user/me

spring:

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/bookshopdb
    username: bookmaster
    password: 1111
    driver-class-name: com.mysql.cj.jdbc.Driver
#    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    hibernate:
    ddl-auto: create
  h2:
    console:
      enable: false
    path: /console
  devtools:
    livereload:
      enable: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 541555327940-in06jhn0n4pu9vrfn42aubbcuoppbsih.apps.googleusercontent.com
            client-secret: Ny_qKOsXUBT5jCDAgQKvTQby

custom:
  oauth2:
    kakao:
      client-id: 9b7e730a78399b4f6d1af01ddd236ff9
